export const INITIAL_RIDES = [
  {
    id: "r1",
    driverName: "Rahul Sharma",
    college: "MLR Institute of Technology",
    gate: "Gate 2 (Main Campus)",
    vehicleType: "Bike",
    vehicleName: "Yamaha FZ (TS 08 AB 1234)",
    departureTime: "08:30 AM",
    pickupLocation: "Gandi Maisamma Junction",
    seatsAvailable: 1,
    costPerSeat: 25,
    genderPreference: "Any",
    isVerifiedStudent: true,
  },
  {
    id: "r2",
    driverName: "Ananya Reddy",
    college: "MLR Institute of Technology",
    gate: "Gate 1 (Aeronautical Block)",
    vehicleType: "Car",
    vehicleName: "Hyundai i20 (TS 07 EQ 9876)",
    departureTime: "08:45 AM",
    pickupLocation: "Suchitra Circle",
    seatsAvailable: 3,
    costPerSeat: 45,
    genderPreference: "Female Only",
    isVerifiedStudent: true,
  },
  {
    id: "r3",
    driverName: "Vikram Kumar",
    college: "MLR Institute of Technology",
    gate: "Gate 3 (Hostel Gate)",
    vehicleType: "Auto Split",
    vehicleName: "Shared Auto",
    departureTime: "09:00 AM",
    pickupLocation: "Kompally Bypass",
    seatsAvailable: 2,
    costPerSeat: 30,
    genderPreference: "Any",
    isVerifiedStudent: true,
  }
];